apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis
spec:
  selector:
    app: evops-user-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
# kubectl apply -f service.yaml  (pour lancer le service)
