Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :vmware_desktop do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the nodejs_server VM
  config.vm.define "nodejs_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "hashicorp/bionic64"
    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    config.vm.synced_folder "../userapi", "/home/userapi"
    # Specify the VM ip address
    server.vm.network :private_network, ip: "20.20.20.2"
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "vmware_desktop" do |vb|
      vb.name =  "nodejs.server.local"
      # VM RAM in MB
      vb.memory = 4096
      # VM CPUs
      vb.cpus = 2
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end
  end
  # View the documentation for the provider you are using for more
  # information on available options.

  # Use Vagrant Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"
    # Only run the roles with these tags
    ansible.tags = "install"
  end
end