name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
       run:
         working-directory: ./userapi/

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Check out repository code
        uses: actions/checkout@v3

    - name: Install dependencies
        run: npm install
    
    - name: Connect to Redis
      run: redis-server
      env:
          REDIS_HOST: redis
          REDIS_PORT: 6379 
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './userapi/package-lock.json'

    - run: npm install
    - run: npm test